const ROLES = require("./roles");
const PERMISSIONS = require("./permissions");

const rolePermissions = {
  [ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_PRODUCTS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.CREATE_SALES,
    PERMISSIONS.VIEW_SALES,
    PERMISSIONS.PRODUCE,
    PERMISSIONS.DISPATCH,

    // 🔥 USUARIOS
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_DELETE,

    // 🔥 PRODUCTOS
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_EDIT,
    PERMISSIONS.PRODUCTS_DELETE,

    // 🔥 INVENTARIO
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_EDIT,
  ],

  [ROLES.VENDEDOR]: [
    PERMISSIONS.CREATE_SALES,
    PERMISSIONS.VIEW_SALES,

    // 🔥 PRODUCTOS
    PERMISSIONS.PRODUCTS_VIEW,
  ],

  [ROLES.HORNERO]: [
    PERMISSIONS.PRODUCE,

    // 🔥 PRODUCTOS
    PERMISSIONS.PRODUCTS_VIEW,
  ],

  [ROLES.DESPACHO]: [
    PERMISSIONS.DISPATCH,

    // 🔥 PRODUCTOS
    PERMISSIONS.PRODUCTS_VIEW,

    // 🔥 INVENTARIO (trazabilidad de lo despachado)
    PERMISSIONS.INVENTORY_VIEW,
  ],

  [ROLES.JEFE_PRODUCCION]: [
    PERMISSIONS.PRODUCE,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.VIEW_DASHBOARD,

    // 🔥 PRODUCTOS
    PERMISSIONS.PRODUCTS_VIEW,

    // 🔥 INVENTARIO
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_EDIT,
  ],
};

module.exports = rolePermissions;